### ISSUE TITLE
Question: DefaultUnitOfWork::startAndGet() using the Monolog object

### ISSUE THREAD

**Issue by mhightower** [SmartGecko/GovernorFramework#10]
In the CommandHandlerExample example there is the line 
````$uow = DefaultUnitOfWork::startAndGet($logger);````
with logger being a Monolog\Logger object
The function currently requires an object with TransactionManagerInterface implemented.
Do you have an example of this? Is Monolog\Logger still needed?

Thanks

**Comment by davidkalosi** [comment]
Hi,

the example is outdated - the UnitOfWork will start with a null logger by default and implements the LoggerAwareInterface which can be used to set the desired logger implementation. the TransactionManagerInterface is optional and can be ommited - there are no implementations of it anyway (other then the NulLTransactionManager) which does nothing.

Can I ask you why do you need to access the UnitOfWork - it is started in the CommandGateway by default and there is rarely a use case to access it directly

david

**Comment by mhightower** [comment]
I'm just following the example in the [CommandHandlerExample](https://github.com/davidkalosi/GovernorFramework/blob/master/example/CommandHandlerExample.php). I wanted to get something working then do the break something, fix it, repeat to see how things connect. If the UnitOfWork lines are not needed then I can just pull it out.

**Comment by davidkalosi** [comment]
in the example the UOW is started just to load back the aggregate and read back the events for the demo purpose (so you can see the actual state of the aggregate right on).

In real life aggregates are loaded as a result of a command that wants to perform an operation so you already have the UOW started.
