### ISSUE TITLE
Upgrade to ProxyManager 1.0.x

### ISSUE THREAD

**Issue by Ocramius** [SmartGecko/GovernorFramework#11]
[ProxyManager 0.5.x](https://github.com/davidkalosi/GovernorFramework/blob/c08bd62b383a974359d012c2879d6aed669f9b3b/composer.json#L13) is not supported anymore, but upgrading should be easy/painless.

**Comment by davidkalosi** [comment]
ok will incorporate that into 0.4.0.

thanks

**Comment by davidkalosi** [comment]
symfony integration was moved to a separate bundle - with updated dependencies - using 1.0.x
