### ISSUE TITLE
Composer install requires php 5.5.* and failes on 5.6

### ISSUE THREAD

**Issue by marcofranssen** [SmartGecko/GovernorFramework#12]
When I install the governor framework using composer I get following error on debian wheezy with php 5.6.

```shell
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for smartgecko/governor-framework dev-master -> satisfiable by smartgecko/governor-framework[dev-master].
    - smartgecko/governor-framework dev-master requires php 5.5.* -> your PHP version (5.6.8-1~dotdeb+wheezy.1) does not satisfy that requirement.
```

Is there any possibility php 5.6 can also be supported. What are you depending on which is deprecated in 5.6?

**Comment by davidkalosi** [comment]
Hi,

I have pushed a new master which can use anything >=5.5 + added 5.6 to travis. builds passed so you should be ready to go with 5.6
